### ISSUE TITLE
Translation Social Media Graphics

### ISSUE THREAD

**Issue by ghost** [Glucosio/brand-assets#1]
We need Glucosio branded with Glucat social media images we can use in posts and tweets to push people to Glucsio Translations.

Requirements: 
- Short call to action encouraging people to visit http://translate.glucosio.org to contribute to Glucosio translations

**Comment by elioqoshi** [comment]
Here we go with Twitter and Facebook!

![facebook banner pink l10n-01](https://cloud.githubusercontent.com/assets/5436686/10220358/2d6cb5a6-6847-11e5-9511-7fb4c121f792.jpg)
![twitter banner pink l10n-01](https://cloud.githubusercontent.com/assets/5436686/10220394/770ea0ac-6847-11e5-81cb-323e3635101c.jpg)
