### ISSUE TITLE
Need 1024x1024 app icon for iOS

### ISSUE THREAD

**Issue by chwalters** [Glucosio/brand-assets#15]
For iOS app store (iTunes connect) we need 1024x1024 app icon (I faked it for now by upscaling 512 x 512 from play store assets)

**Comment by elioqoshi** [comment]
![ios-01](https://cloud.githubusercontent.com/assets/5436686/17560268/b4a250f4-5f21-11e6-99b6-9c183682603c.png)

Sorry for the delay, here we go
