### ISSUE TITLE
Amazon Store Assets

### ISSUE THREAD

**Issue by ghost** [Glucosio/brand-assets#3]
Small icon
114 x 114px PNG (with transparency)

Between 3 and 10 PNGs or JPGs
800 x 480px, 1024 x 600px, 1280 x 720px,
1280 x 800px, 1920 x 1080px, 1920 x 1200px,
or 2560 x 1600px (portrait or landscape)

Promotional image (Recommended)
1024 x 500px (landscape only) PNG or JPG

**Comment by elioqoshi** [comment]
Will try to do these on Sunday
