### ISSUE TITLE
Social Media Assets

### ISSUE THREAD

**Issue by ghost** [Glucosio/brand-assets#4]
@birajkarmakar needs social media post templates

**Comment by birajkarmakar** [comment]
It would be good to have below things

1.Glucat in png format
2.Logo in png format
3.High resolution background
4.Some high resolution screenshot

**Comment by elioqoshi** [comment]
You can find all branding (including Glucat and Logo) on Brandisty:
https://brandisty.com/glucosio

Here is the background.
![background-01](https://cloud.githubusercontent.com/assets/5436686/10717045/6b51f422-7b4c-11e5-8534-08c45cdce6dc.jpg)

The screenshots should be somewhere here on GitHub. @bkerensa ?

**Comment by ghost** [comment]
@elioqoshi I just uploaded everything I have I think we just need Glucate with transparent bg and Biraj should be able to go. Can you remind me what font we should use on social media images so I can add that to the creative guide?

**Comment by elioqoshi** [comment]
@bkerensa As I said, the assets are on Brandisty and can be downloaded also as PNG

Lato is the font we use for images (Lato Light to be specific)

**Comment by birajkarmakar** [comment]
@bkerensa,it  would be good if you provide some screenshot sample.

@elioqoshi thanks.

**Comment by ghost** [comment]
There are screen shots in the brand folder
